services:
  - type: web
    name: central-smart-home
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NEWS_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
    autoDeploy: true